### ISSUE TITLE
Splunk Cloud compatibility

### ISSUE THREAD

**Issue by dgcom** [dmanojbaba/splunk-command-newrelic-nrql#1]
Can this app be certified for Splunk Cloud?
With current Splunk versions, Python v3 is required.

I requested this app to be vetted for Splunk Cloud, but it failed:

> [failure] Check that python version is python3 for executables in restmap.conf. 
> •	The handler of stanza [admin_external:nrql_connections] should be `python3` executable. File: default/restmap.conf Line Number: 5

Also, according to the documentation, commands.conf need the following line added:
`python.version = python3`

**Comment by dmanojbaba** [comment]
Fixed in version 1.0.2. Now available in Splunkbase.
